notifications:
  slack:
    secure: ECND9JC2WAYuuqjvCB5NBNikS5RgPzVqEwKN9W/Mex3J3mtYihjQdCEKXv3dtc8hXcIIvPzPWgiC4/ei82ZHW5SiPOSXBW0TKhrWHVuA8NCg3Hb9YzVqi+9lIL5gnXEZA2I57sTevoQDdu4dPMYcKy+nNWTgnNHo5XOPjITnSOG+JXfTizBg4zMWEWpvZLPIocj9Y21RjHV5YqrTWG9ve5yJyH9NYFH1TB3wfTi+hRpEEAxgtOcM0IxS2RuapE5awaRT8LtCrRYNPfjAmUvs5dE3gZ81t0BvFuxwL/I0VKg1A/wmZfFLM8Ug7tPmRTEqZ14T2Eks4ZyxmbC2Gcyei6zbdquYeDp5cUC09BOD8KPAHMha+bWRZigAJ2HLv8mIBuLiP86N/U+XysksQnx0l12HBiOoCIxjHXDgrMdDr6lyzCTbM3cN+4921lYRPBz3as8WOY7tj16AsvlY/wsQRrCMb28MReait1LckggHHIFflNhTnM0vTD/uw1EaEHslUuQVFcC44ADWVY5Z1yrYk9bH0DgySQ9JX9/ZPbS8d/a8B+ed2j9w1dJMusEV1SAkSF3z22jwxesUDXAeBWd8vd6CxZYcZQIglxwVWSAXAuYCHBRqfcC2XffGNLARSxe28G6NFGP/0Hxn9jCmf7N3HymjRPWNauqczoRD9PHfRhQ=

language: c
dist: xenial
env: HOLBA_OPT_DIR=$HOME/cache

cache:
  directories:
    - $HOME/cache

jobs:
  include:
    - stage: "Prepare all cached dependencies"
      before_script:
        - scripts/setup/install_base.sh
      script:
        - true

    - stage: "Compile and test"
      script:
        - scripts/ci/run_make.sh main
        - scripts/ci/run_make.sh tests


