notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: ECND9JC2WAYuuqjvCB5NBNikS5RgPzVqEwKN9W/Mex3J3mtYihjQdCEKXv3dtc8hXcIIvPzPWgiC4/ei82ZHW5SiPOSXBW0TKhrWHVuA8NCg3Hb9YzVqi+9lIL5gnXEZA2I57sTevoQDdu4dPMYcKy+nNWTgnNHo5XOPjITnSOG+JXfTizBg4zMWEWpvZLPIocj9Y21RjHV5YqrTWG9ve5yJyH9NYFH1TB3wfTi+hRpEEAxgtOcM0IxS2RuapE5awaRT8LtCrRYNPfjAmUvs5dE3gZ81t0BvFuxwL/I0VKg1A/wmZfFLM8Ug7tPmRTEqZ14T2Eks4ZyxmbC2Gcyei6zbdquYeDp5cUC09BOD8KPAHMha+bWRZigAJ2HLv8mIBuLiP86N/U+XysksQnx0l12HBiOoCIxjHXDgrMdDr6lyzCTbM3cN+4921lYRPBz3as8WOY7tj16AsvlY/wsQRrCMb28MReait1LckggHHIFflNhTnM0vTD/uw1EaEHslUuQVFcC44ADWVY5Z1yrYk9bH0DgySQ9JX9/ZPbS8d/a8B+ed2j9w1dJMusEV1SAkSF3z22jwxesUDXAeBWd8vd6CxZYcZQIglxwVWSAXAuYCHBRqfcC2XffGNLARSxe28G6NFGP/0Hxn9jCmf7N3HymjRPWNauqczoRD9PHfRhQ=

language: c
dist: xenial
env:
  global:
    - HOLBA_OPT_DIR=$HOME/cache
    - secure: M4nFRCjPs4zCHwE0m3hb9PtU603+V8NtcgBCu39iMsW5bvd5/SzdZNOss/JcV6WckwbTkqwsJPqUL83b/mTzWItVdexIHnaBw0BIu1vsAMSzJFPDlDvpOjmvTLZZ8mp9YBQwODUaLY4J5yrOU1ODsuTyBWidIyeVWIFYG7FB0Gv+wygh7hHgVL2eCRzwCJ0vfrOlORd/Tkmfvf5gTdUR82ZvPmBKiHoyCfNhgRlUAeiUZQLtBFvcdUq2L/mUFSaOe1o6KJewN+xczqA6w3X63dE7Pfm8CImAbgxKSp/GwMDmMGrmH1DmXHlWI7nNgA779tDfma+ozJd7MuPeXpmijTfmExqlZEFECf/epVsQuYE2FCu066+aAsSu0Pf/qv/kqwfyNWJula4EpoQywYm7PKL0SLDhb9ydb/Az7/1LlUvDP8TY0Q6Jksz9Yeu9uocO7mg+eiEv28usPc+eoevSEqh/GYxOcBWclVHWPT4lgW8g2wlrYdslmKVRgw9ufn9YrmOczLLRAhlXqkDkpED5MNXdWwx2Pt7fCnDxsoTGV4p2xhK/yKCdNHoK0wfZHbIks0IBz7+5yJWl3XKiM7bAQfMnpb7XBKzOwgc7oVW6Ah0I+NH50302hlz8mE4gp+y1alQzJyr1F3y4lWcflKSrjJqNdQ+y4tYd/vCZ7rWPtCg=

cache:
  directories:
    - $HOME/cache

jobs:
  include:
    - stage: "Static analysis"
      script:
        - scripts/ci/grep-cheat-comment-PR.sh

    - &cache-prep
      stage: "Prepare all cached dependencies"
      before_script:
        - scripts/setup/install_base.sh
        - scripts/setup/install_z3.sh
      script:
        - true

    - <<: *cache-prep
      env: HOLBA_POLYML_VERSION="v5.8"

    - &compile-test
      stage: "Compile and test"
      script:
        - scripts/ci/run_make.sh main
        - scripts/ci/run_make.sh tests

    - <<: *compile-test
      env: HOLBA_POLYML_VERSION="v5.8"


