name: CI Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  HOLBA_OPT_DIR: /home/runner/cache
  HOLBA_BOT_GITHUB_TOKEN: 'comment. see scripts/ci/post-comment-on-PR.sh, use github actions secrets'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        polyml: ['v5.7.1', 'v5.8.1']
        hol4: ['kananaskis-14']

    env:
      HOLBA_POLYML_VERSION: ${{ matrix.polyml }}
      HOLBA_HOL4_VERSION: ${{ matrix.hol4 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.HOLBA_OPT_DIR }}
          key: os-${{ runner.os }}_polyml-${{ matrix.polyml }}_hol4-${{ matrix.hol4 }}

      - name: Static analysis
        timeout-minutes: 5
        run: |
          ./scripts/ci/static-analysis.sh || echo "Static-analysis failed with status $?."

      - name: Prepare cached dependencies
        timeout-minutes: 35
        run: |
          ./scripts/setup/install_base.sh
          ./scripts/setup/install_z3.sh

      - name: Configure and compile
        timeout-minutes: 35
        run: |
          ./configure.sh
          ./scripts/ci/run_make.sh main

      - name: Run tests
        timeout-minutes: 35
        run: |
          ./scripts/ci/run_make.sh tests


